routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/', 'UserController@index')->name('index');

Route::post('user/portfolio', 'UserController@modal')->name('portfolio.index');

Route::post('contact/send', 'ContactController@store')->name('contact.send');



    Route::get('/login', 'LoginController@index')->name('login')->middleware('guest');

    Route::post('/login/check', 'LoginController@login_check')->name('login.check');

    Route::get('logout', 'LoginController@logout')->name('logout');



Route::group(['middleware' => ['auth']], function () {

    Route::get('admin', 'AdminController@index')->name('admin.index');

    Route::get('admin/ajax', 'AdminController@ajax')->name('admin.ajax');

    Route::post('admin/changes', 'AdminController@changes')->name('admin.changes');

    Route::resource('contacts', 'ContactController');

    Route::post('contacts/ajax', 'ContactController@ajax')->name('contact.show');

    Route::post('contact/show', 'ContactController@show')->name('contact.show');

    Route::post('contact/answer', 'ContactController@contact_answer')->name('contact.answer');

    Route::get('subscribers/show', 'SubscribersController@index')->name('subscribers');

    Route::post('subscribers/email', 'SubscribersController@send_email')->name('subscribers.email');

    Route::resource('category','CategoryController');

    Route::resource('portfolio','PortfolioController');

    Route::post('portfolio/update', 'portfolioController@update')->name('portfolio.update');

    Route::resource('testimonials','TestimonialsController');

    Route::post('testimonials/ajax','TestimonialsController@ajax')->name('testimonials.ajax');

    Route::post('testimonials/show','TestimonialsController@show')->name('testimonials.show');

    Route::post('portfolio/ajax','PortfolioController@ajax')->name('portfolio.ajax');
});




Route::post('subscribe/store', 'SubscribersController@store')->name('subscribe.store');
Route::get('subscribe/verification', 'SubscribersController@verification')->name('subscribe.verification');

resources/views/admin/contacts.blade.php
@extends('admin.template.main')

@section('content')
    <script src="{{asset('admin_assets/dist/js/js_pages/contacts.js')}}"></script>

    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-5 align-self-center">
                    <h4 class="page-title">Contacts</h4>
                </div>

            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th class="border-top-0">NAME</th>
                                    <th class="border-top-0">Email</th>
                                    <th class="border-top-0">Subject</th>
                                    <th class="border-top-0">Message</th>
                                </tr>
                                </thead>
                                <tbody id="contact_show">
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>

    <!-- ============================================================== -->
    <!-- End PAge Content -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Right sidebar -->
    <!-- ============================================================== -->
    <!-- .right-sidebar -->
    <!-- ============================================================== -->
    <!-- End Right sidebar -->
    <!-- ============================================================== -->
    </div>


    @include('admin.layouts.modal_contact')

@endsection

resources/views/admin/index.blade.php
@extends('admin.template.main')

@section('content')
    <script src="{{asset('admin_assets/dist/js/js_pages/profile.js')}}"></script>

    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-5 align-self-center">
                    <h4 class="page-title">Profile</h4>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <!-- Row -->
            <form action="{{route('admin.changes')}}" method="post" class="form-horizontal form-material" id="admin_changes"  enctype="multipart/form-data">
                @csrf
            <div class="row">
                <!-- Column -->
                <div class="col-lg-4 col-xlg-3 col-md-5">
                    <div class="card">
                        <div class="card-body">
                            <center class="m-t-30" id="cropper-div">
                                    <input type="hidden" value="{{asset('admin_assets/assets/images/users/'.$info->image)}}" id="profile_image_old_hidden"/>
                                    <img src="{{asset('admin_assets/assets/images/users/'.$info->image)}}" class="rounded-circle profile_image" width="150" id="profile_image" />

                            </center>
                            <center id="image-div">
                                <h4 class="card-title m-t-10">{{$info->name}}</h4>
                                <label class="btn btn-danger" id="delete_profile_image_btn">
                                    x<input type="button" hidden id="delete_profile_image">
                                </label>
                                <label class="btn btn-danger" id="hide_image_cropper">
                                    x<input type="button" hidden >
                                </label>
                                <label class="btn btn-default" id="add_profile_image_btn">
                                    v<input  type="button" hidden id="add_profile_image">
                                </label>
                            </center>
                        </div>
                        <hr>
                        <div class="card-footer">
                            <center>
                                <label class="btn btn-default" id="image-lable">
                                    Change Profile Image <input  type="file" hidden class='image-validate' id="profile_image_input" name="image">
                                </label>
                            </center>



                        </div>
                    </div>
                </div>
                <!-- Column -->
                <!-- Column -->
                <div class="col-lg-8 col-xlg-9 col-md-7">
                    <div class="card">
                        <div class="card-body" id="valid-1">


                                <div class="form-group">
                                    <label class="col-md-12">Full Name</label>
                                    <div class="col-md-12">
                                        <input type="text" name="name" value="{{$info->name}}" class="form-control form-control-line">
                                        <p id="name_validate" style="color: red"><?php echo $errors->has('name') ? 'please enter your name' : '';?></p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12">Login</label>
                                    <div class="col-md-12">
                                        <input type="text" name="login" value="{{$info->login}}" class="form-control form-control-line">
                                        <p id="login_validate" style="color: red"><?php echo $errors->has('login') ? 'please enter your login' : '';?></p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12">Old Password</label>
                                    <div class="col-md-12">
                                        <input type="password" name="old_password" class="form-control form-control-line" id="old_password">
                                        <p id="first_p_validate" style="color: red"><?php echo $errors->has('old_password') ? 'please enter your old password' : '';?></p>

                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-12">New Password</label>
                                    <div class="col-md-12">
                                        <input type="password" name="new_password" class="form-control form-control-line" id="new_password">
                                        <p id="second_p_validate" style="color:red"><?php echo (session()->has('password_error')) ? session()->get('password_error') : '';?></p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="hidden" name="profile_image" id="hidden_image_input">
                                </div>

                                <div class="form-group float-right">
                                    <div class="col-sm-12">
                                        <img id="changes_loading" src="{{asset('images/loading.gif')}}" alt="loading..." class="contact_loading" width="25" style="display: none;">
                                        <button type="submit" class="btn btn-primary">Save Changes</button>
                                    </div>
                                    @if($message = Session::get('login_error'))
                                        <p style="color:red">{{$message}}</p>
                                    @endif
                                </div>

                        </div>
                    </div>
                </div>
                <!-- Column -->
            </div>
            </form>
            <!-- Row -->
            <!-- ============================================================== -->
            <!-- End PAge Content -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Right sidebar -->
            <!-- ============================================================== -->
            <!-- .right-sidebar -->
            <!-- ============================================================== -->
            <!-- End Right sidebar -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>

    <!-- ============================================================== -->
    <!-- End PAge Content -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Right sidebar -->
    <!-- ============================================================== -->
    <!-- .right-sidebar -->
    <!-- ============================================================== -->
    <!-- End Right sidebar -->
    <!-- ============================================================== -->
    </div>

    @include('admin.layouts.modal_add_portfolio')
    @include('admin.layouts.modal_edit_portfolio')

@endsection

resources/views/admin/portfolio.blade.php
@extends('admin.template.main')

@section('content')
    <script src="{{asset('admin_assets/dist/js/js_pages/portfolio.js')}}"></script>

    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-5 align-self-center">
                    <h4 class="page-title">Portfolio</h4>
                </div>

            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div style="display: inline">
                            <div class="float-left"><button type="button" class="add" data-toggle="modal" data-target="#add_portfolio_modal" ><i class="fa fa-plus" aria-hidden="true"></i></button></div>
                            <div class="float-right"><button type="button" class="add" data-toggle="modal" data-target="#category_p_modal" ><i class="mdi mdi-layers"></i></button></div>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col"></th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Description</th>
                                    <th scope="col">Category</th>
                                    <th scope="col"></th>
                                </tr>
                                </thead>
                                <tbody id="portfolio_list">
{{--                                @foreach($portfolios as $portfolio)--}}
{{--                                    <tr>--}}
{{--                                        <td><img src="{{asset('images/portfolio_images/' . $portfolio->image)}}" alt="portfolio image" width="100px"></td>--}}
{{--                                        <td>{{$portfolio->title}}</td>--}}
{{--                                        <td> {{substr($portfolio->description,0,25)}} <button type="button" class="show_more" id="{{$portfolio->id}}">. . .</button></td>--}}
{{--                                        <td>{{$portfolio->category}}</td>--}}
{{--                                        <td   style="float: right; border: 0;">--}}
{{--                                            <button type="button" class="edit" data-toggle="modal" data-target="#exampleModal_2"  ><i class="fa fa-pencil-square-o p_edit" aria-hidden="true" style="font-size:24px"></i></button>--}}
{{--                                            <button type="button" href="{{route('portfolio.destroy', $portfolio->id)}}" class="edit trash_portfolio" id="{{'portfolio-'.$portfolio->id}}"><i class="fa fa-trash p_delete" aria-hidden="true" style="font-size:24px"></i></button>--}}
{{--                                        </td>--}}

{{--                                    </tr>--}}<i class="fas fa-network-wired"></i>
{{--                                @endforeach--}}
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- ============================================================== -->
    <!-- End PAge Content -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Right sidebar -->
    <!-- ============================================================== -->
    <!-- .right-sidebar -->
    <!-- ============================================================== -->
    <!-- End Right sidebar -->
    <!-- ============================================================== -->
    </div>
    @include('admin.layouts.modal_category_p')
    @include('admin.layouts.modal_add_portfolio')
    @include('admin.layouts.modal_edit_portfolio')

@endsection

resources/views/admin/subscribers.blade.php
@extends('admin.template.main')

@section('content')
    <script src="{{asset('admin_assets/dist/js/js_pages/subscribers.js')}}"></script>

    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-5 align-self-center">
                    <h4 class="page-title">Subscribers</h4>
                </div>

            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-12">
                    <div class="card p-4">

                        <div>
                            <button type="button" class="edit float-right" data-toggle="modal" data-target="#exampleModal_3"  ><i class="fa fa-list p_edit" aria-hidden="true" style="font-size:24px"></i></button>
                        </div>

                        <form action="{{route('subscribers.email')}}" method="post" id="subscribers_email_send">
                            @csrf
                            <div class="form-group">
                                <label for="exampleInputTo">To</label>
                                <input  type="text" class="form-control" id="exampleInputTo" value="All Subscribers" readonly="readonly" >
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">Subject<?php echo $errors->has('subject') ? '<div style="color:red;    display: inline;" >*</div>' : '';?></label>
                                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter Subject" name="subject" >
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlTextarea">Message<?php echo $errors->has('message') ? '<div style="color:red;    display: inline;" >*</div>' : '';?></label>
                                <textarea class="form-control rounded-0" id="exampleFormControlTextarea" rows="5" placeholder="Enter Message" name="message" ></textarea>
                            </div>

                            <div class="float-right">
                                <button type="submit" class="btn btn-primary float-right">Send Messages</button>
                                <img id="loading" src="{{asset('images/loading.gif')}}" width="40px" height="40px" alt="please wait" style="display: none">
                            </div>

                        </form>
                        @include('admin.layouts.modal_subscribers_list')

{{--                        <div class="table-responsive">--}}
{{--                            <table class="table">--}}
{{--                                <thead>--}}
{{--                                <tr>--}}
{{--                                    <th scope="col">Email</th>--}}
{{--                                    <th></th>--}}
{{--                                </tr>--}}
{{--                                </thead>--}}
{{--                                <tbody>--}}

{{--                                @foreach($subscribers as $subscriber)--}}
{{--                                <tr>--}}

{{--                                    <td>{{$subscriber->email}}</td>--}}
{{--                                    <td   style="float: right; border: 0;">--}}
{{--                                        <i class="fa fa-times p_delete" aria-hidden="true" style="font-size:24px"></i>--}}

{{--                                        <button type="button" class="edit" data-toggle="modal" data-target="#exampleModal_2"  ><i class="fa fa-pencil-square-o p_edit" aria-hidden="true" style="font-size:24px"></i></button>--}}

{{--                                    </td>--}}

{{--                                </tr>--}}
{{--                               @endforeach--}}
{{--                                </tbody>--}}
{{--                            </table>--}}
{{--                        </div>--}}

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- ============================================================== -->
    <!-- End PAge Content -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Right sidebar -->
    <!-- ============================================================== -->
    <!-- .right-sidebar -->
    <!-- ============================================================== -->
    <!-- End Right sidebar -->
    <!-- ============================================================== -->
    </div>

    @include('admin.layouts.modal_add_portfolio')
    @include('admin.layouts.modal_edit_portfolio')

@endsection

resources/views/admin/testimonials.blade.php
@extends('admin.template.main')

@section('content')
    <script src="{{asset('admin_assets/dist/js/js_pages/testimonials.js')}}"></script>

    <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-5 align-self-center">
                    <h4 class="page-title">Testimonials</h4>
                </div>

            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            <!-- ============================================================== -->
            <!-- Start Page Content -->
            <!-- ============================================================== -->
            <div class="row">
                <div class="col-12">
                    <div class="card">

                        <h6 class="card-title m-t-40" style="margin-top: 10px;"><button type="button" class="add" data-toggle="modal" data-target="#add_testimonials_modal" ><i class="fa fa-plus" aria-hidden="true"></i></button></h6>

                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th scope="col"></th>
                                    <th scope="col">Admin Name</th>
                                    <th scope="col">Text</th>
                                    <th scope="col"></th>
                                </tr>
                                </thead>
                                <tbody id="testimonial_list">
{{--                                @foreach($portfolios as $portfolio)--}}
{{--                                    <tr>--}}
{{--                                        <td><img src="{{asset('images/portfolio_images/' . $portfolio->image)}}" alt="portfolio image" width="100px"></td>--}}
{{--                                        <td>{{$portfolio->title}}</td>--}}
{{--                                        <td> {{substr($portfolio->description,0,25)}} <button type="button" class="show_more" id="{{$portfolio->id}}">. . .</button></td>--}}
{{--                                        <td>{{$portfolio->category}}</td>--}}
{{--                                        <td   style="float: right; border: 0;">--}}
{{--                                            <button type="button" class="edit" data-toggle="modal" data-target="#exampleModal_2"  ><i class="fa fa-pencil-square-o p_edit" aria-hidden="true" style="font-size:24px"></i></button>--}}
{{--                                            <button type="button" href="{{route('portfolio.destroy', $portfolio->id)}}" class="edit trash_portfolio" id="{{'portfolio-'.$portfolio->id}}"><i class="fa fa-trash p_delete" aria-hidden="true" style="font-size:24px"></i></button>--}}
{{--                                        </td>--}}

{{--                                    </tr>--}}
{{--                                @endforeach--}}
                                </tbody>
                            </table>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- ============================================================== -->
    <!-- End PAge Content -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Right sidebar -->
    <!-- ============================================================== -->
    <!-- .right-sidebar -->
    <!-- ============================================================== -->
    <!-- End Right sidebar -->
    <!-- ============================================================== -->
    </div>

    @include('admin.layouts.modal_add_testimonials')
    @include('admin.layouts.modal_testimonial_show')

@endsection