routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::get('/', 'UserController@index')->name('index');

Route::post('user/portfolio', 'UserController@modal')->name('portfolio.index');

Route::post('contact/send', 'ContactController@store')->name('contact.send');



    Route::get('/login', 'LoginController@index')->name('login')->middleware('guest');

    Route::post('/login/check', 'LoginController@login_check')->name('login.check');

    Route::get('logout', 'LoginController@logout')->name('logout');



Route::group(['middleware' => ['auth']], function () {

    Route::get('admin', 'AdminController@index')->name('admin.index');

    Route::get('admin/ajax', 'AdminController@ajax')->name('admin.ajax');

    Route::post('admin/changes', 'AdminController@changes')->name('admin.changes');

    Route::resource('contacts', 'ContactController');

    Route::post('contacts/ajax', 'ContactController@ajax')->name('contact.show');

    Route::post('contact/show', 'ContactController@show')->name('contact.show');

    Route::post('contact/answer', 'ContactController@contact_answer')->name('contact.answer');

    Route::get('subscribers/show', 'SubscribersController@index')->name('subscribers');

    Route::post('subscribers/email', 'SubscribersController@send_email')->name('subscribers.email');

    Route::resource('category','CategoryController');

    Route::resource('portfolio','PortfolioController');

    Route::post('portfolio/update', 'portfolioController@update')->name('portfolio.update');

    Route::resource('testimonials','TestimonialsController');

    Route::post('testimonials/ajax','TestimonialsController@ajax')->name('testimonials.ajax');

    Route::post('testimonials/show','TestimonialsController@show')->name('testimonials.show');

    Route::post('portfolio/ajax','PortfolioController@ajax')->name('portfolio.ajax');
});




Route::post('subscribe/store', 'SubscribersController@store')->name('subscribe.store');
Route::get('subscribe/verification', 'SubscribersController@verification')->name('subscribe.verification');

resources/views/admin/layouts/aside.blade.php
        <aside class="left-sidebar" data-sidebarbg="skin5">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('portfolio.index')}}" aria-expanded="false">

                                <span class="hide-menu">Portfolio</span>
                            </a>
                        </li>
                        
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('contacts.index')}}" aria-expanded="false">

                                <span class="hide-menu">Contacts</span>
                            </a>
                        </li>

                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('subscribers')}}" aria-expanded="false">

                                <span class="hide-menu">Subscribers</span>
                            </a>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{route('testimonials.index')}}" aria-expanded="false">

                                <span class="hide-menu">Testimonials</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>

resources/views/admin/layouts/footer.blade.php
            <footer class="footer text-center">
                All Rights Reserved by Nice admin. Designed and Developed by
                <a href="https://wrappixel.com">WrapPixel</a>.
            </footer>

resources/views/admin/layouts/modal_add_portfolio.blade.php
            <div class="modal fade" id="add_portfolio_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Portfolio</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

    <div class="modal-body">
        <form action="{{route('portfolio.store')}}" id="add_portfolio_form">
          @csrf
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Title:</label>
            <input type="text" class="form-control" id="recipient-name" name="title" >
            <p style="color: red" id="portfolio_error"></p>
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Description:</label>
            <textarea class="form-control" id="message-text" name="description"></textarea>
          </div>
          <div class="form-group">
            <select name="category_id" class="form-control" id="category_p_select">
              <option value="1">uncategory</option>
            </select>

          </div>
          <div class="form-group">
          <div class="custom-file mb-3" style="margin-top: 14px">
            <input type="file" class="custom-file-input" name="file" id="portfolio-add-img">
            <label class="custom-file-label" for="customFile" >Choose file</label>
        {{--      <input type="file" name="file" id="profile-img">--}}
            <img src="" id="portfolio-add-img-tag" width="100px" alt="hear will be image" />

          </div>
          </div>




          <button type="submit" class="btn btn-success float-right">Add Portfolio</button>

        </form>


      </div>
    </div>
  </div>
</div>

resources/views/admin/layouts/modal_add_testimonials.blade.php
<div class="modal fade" id="add_testimonials_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Testimonial</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

    <div class="modal-body">
        <form action="{{route('testimonials.store')}}" id="add_testimonial_form">
          @csrf
          <div class="form-group">
            <label for="testimonial-text" class="col-form-label">Testimonial:</label>
            <textarea class="form-control" id="testimonial-text" name="testimonial"></textarea>
          </div>
          <button type="submit" class="btn btn-success float-right">Add Testimonial</button>
        </form>


      </div>
    </div>
  </div>
</div>

resources/views/admin/layouts/modal_category_p.blade.php
<!-- Modal -->
<div class="modal fade" id="category_p_modal" tabindex="-1" role="dialog" aria-labelledby="category_p" aria-hidden="true" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Portfolio Categories</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">

        <div id="category_p_list">
        </div>
        <hr>
        <form action="{{route('category.store')}}" id="add_category_form">
          @csrf
          <input type="text" name="category_name" placeholder="Category name" id="subemail">
          <button type="submit" class="btn btn-primary">+</button>
        </form>
      <div class="category_error"></div>





    </div>
  </div>
</div>
</div>

resources/views/admin/layouts/modal_contact.blade.php
<!-- Modal -->
<div class="modal fade" id="contact_answer_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body modal-content">
          <p class="modal-message">
        </p>


        <form action="{{route('contact.answer')}}" method="post" id="contact_answer">
          @csrf
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Subject:</label>
            <input type="text" class="form-control" id="recipient-name" value="Contact Answer"  name="subject">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text" name="message" ></textarea>
          </div>

          <input type="hidden" id="contact-id" name="id">
          <input type="hidden" id="contact-name" name="name">
          <input type="hidden" id="contact-email" name="email">
          <div class="modal-footer">
            <img src="{{asset('images/loading.gif')}}" alt="loading..." class="contact_loading" width="38" style="display: none;">
            <button type="submit" class="btn btn-primary">Send message</button>
          </div>
        </form>


    </div>
  </div>
</div>
</div>

resources/views/admin/layouts/modal_edit_portfolio.blade.php
<div class="modal fade" id="edit_portfolio_modal" tabindex="-1" role="dialog" aria-labelledby="edit_portfolio_modal_Lable" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Portfolio</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>


        <div class="modal-body">
            <form action="{{route('portfolio.update')}}" id="edit_portfolio_form">
                @csrf
                <input type="hidden" id="edit_portfolio_id" name="portfolio_id" >
                <div class="form-group">
                    <label for="recipient-name" class="col-form-label">Title:</label>
                    <input type="text" class="form-control" id="edit_portfolio_title" name="title" >
                    <p id="title_error" style="color:red"></p>
                </div>
                <div class="form-group">
                    <label for="message-text" class="col-form-label">Description:</label>
                    <textarea class="form-control" id="edit_portfolio_description" name="description"></textarea>
                    <p id="description_error" style="color:red"></p>
                </div>
                <div class="form-group">
                    <select name="category_id" class="form-control" id="category_p_select_edit">
                        <option value="1">uncategory</option>
                    </select>

                </div>
                <div class="form-group">
                    <div class="custom-file mb-3" style="margin-top: 14px">
                        <input type="file" class="custom-file-input" name="file" id="portfolio-edit-img">
                        <label class="custom-file-label" for="customFile" >Change image</label>
                        {{--      <input type="file" name="file" id="profile-img">--}}
                        <img src="" id="portfolio-img-tag" width="100px" alt="hear will be image" />

                    </div>
                </div>

                <button type="submit" class="btn btn-success float-right">Save Edits</button>
            </form>


        </div>

    </div>
  </div>
</div>

resources/views/admin/layouts/modal_subscribers_list.blade.php
<!-- Modal -->
<div class="modal fade" id="exampleModal_3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Subscribers</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">


        @for ($i = count($subscribers)-1; $i >= 0; $i--)

            <p>- {{$subscribers[$i]->email}}</p>

        @endfor



    </div>
  </div>
</div>
</div>

resources/views/admin/layouts/modal_testimonial_show.blade.php
<!-- Modal -->
<div class="modal fade" id="testimonial_show" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Testimonial</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <p id="testimonial_text"></p>

    </div>
  </div>
</div>
</div>